builds:
  - binary: dgr
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: Dagger
    homepage: https://github.com/mikkurogue/dagger-cli
    commit_author:
      name: Mikku
      email: michael.lindemans@outlook.com
    repository:
      owner: mikkurogue
      name: homebrew-mikkurogue
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "lib/custom_download_strategy"

checksum:
  name_template: "checksums.txt"
