name: goreleaser

builds:
 - binary: bigmile-cli
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
  env:
    - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: bigmile-cli
    homepage: https://bigmile.eu
    tap:
      owner: mikkurogue
      name: homebrew-mikkurogue
      commit_author:
        name: Mikku
        email: michael.lindemans@outlook.com

checksum:
  name_template: 'bigmile-cli-checksums.txt'