builds:
  - binary: bigmile-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: bigmile-cli
    homepage: https:/bigmile.eu
    commit_author:
      name: Mikku
      email: michael.lindemans@outlook.com
    repository:
      owner: mikkurogue
      name: homebrew-mikkurogue
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "lib/custom_download_strategy"

checksum:
  name_template: "checksums.txt"
